// <auto-generated />
using System;
using AzureDevOpsAgents.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzureDevOpsAgents.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303005040_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("AzureDevOpsAgents.Api.Data.Entities.AgentJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Log")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RepoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultUrl")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkItemTitle")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepoId");

                    b.HasIndex("SessionId");

                    b.ToTable("AgentJobs");
                });

            modelBuilder.Entity("AzureDevOpsAgents.Api.Data.Entities.AzureDevOpsConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("AzureDevOpsAgents.Api.Data.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("AzureDevOpsAgents.Api.Data.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("AzureDevOpsAgents.Api.Data.Entities.ProjectRepo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CloneError")
                        .HasColumnType("TEXT");

                    b.Property<string>("CloneStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClonedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalClonePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepoName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.ToTable("Repos");
                });

            modelBuilder.Entity("AzureDevOpsAgents.Api.Data.Entities.AgentJob", b =>
                {
                    b.HasOne("AzureDevOpsAgents.Api.Data.Entities.ProjectRepo", "Repo")
                        .WithMany("AgentJobs")
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AzureDevOpsAgents.Api.Data.Entities.ChatSession", "Session")
                        .WithMany("AgentJobs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repo");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AzureDevOpsAgents.Api.Data.Entities.ChatMessage", b =>
                {
                    b.HasOne("AzureDevOpsAgents.Api.Data.Entities.ChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AzureDevOpsAgents.Api.Data.Entities.ChatSession", b =>
                {
                    b.HasOne("AzureDevOpsAgents.Api.Data.Entities.AzureDevOpsConnection", "Connection")
                        .WithMany("ChatSessions")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("AzureDevOpsAgents.Api.Data.Entities.ProjectRepo", b =>
                {
                    b.HasOne("AzureDevOpsAgents.Api.Data.Entities.AzureDevOpsConnection", "Connection")
                        .WithMany("Repos")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("AzureDevOpsAgents.Api.Data.Entities.AzureDevOpsConnection", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("Repos");
                });

            modelBuilder.Entity("AzureDevOpsAgents.Api.Data.Entities.ChatSession", b =>
                {
                    b.Navigation("AgentJobs");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AzureDevOpsAgents.Api.Data.Entities.ProjectRepo", b =>
                {
                    b.Navigation("AgentJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
